package com.ectoplasmator;

import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import lombok.AccessLevel;
import lombok.Getter;
import net.runelite.api.NpcID;

public class SpectralCreatures
{
	@Getter(AccessLevel.PACKAGE)
	private final List<Integer> SpectralCreatures = new ArrayList<>();

	// CONSTRUCTOR // Populates the NPC list
	// Ideally this would be by querying the npc type (spectral) but this can't be done with the runelite
	// API as it's considered cheating.
	// Instead, the wiki was used to make this list:
	// https://oldschool.runescape.wiki/w/Spectral_(attribute)
	@Inject
	private SpectralCreatures()
	{
		SpectralCreatures.clear();
		SpectralCreatures.add(NpcID.ABERRANT_SPECTRE);
		SpectralCreatures.add(NpcID.ABERRANT_SPECTRE_3);
		SpectralCreatures.add(NpcID.ABERRANT_SPECTRE_4);
		SpectralCreatures.add(NpcID.ABERRANT_SPECTRE_5);
		SpectralCreatures.add(NpcID.ABERRANT_SPECTRE_6);
		SpectralCreatures.add(NpcID.ABERRANT_SPECTRE_7);
		SpectralCreatures.add(NpcID.ABHORRENT_SPECTRE);
		SpectralCreatures.add(NpcID.AHRIM_THE_BLIGHTED);
		SpectralCreatures.add(NpcID.AHRIM_THE_BLIGHTED_12316);
		SpectralCreatures.add(NpcID.AHRIM_THE_BLIGHTED_12322);
		SpectralCreatures.add(NpcID.ANGRY_BARBARIAN_SPIRIT);
		SpectralCreatures.add(NpcID.ANKOU);
		SpectralCreatures.add(NpcID.ANKOU_2515);
		SpectralCreatures.add(NpcID.ANKOU_2516);
		SpectralCreatures.add(NpcID.ANKOU_2517);
		SpectralCreatures.add(NpcID.ANKOU_2518);
		SpectralCreatures.add(NpcID.ANKOU_2519);
		SpectralCreatures.add(NpcID.ANKOU_6608);
		SpectralCreatures.add(NpcID.ANKOU_7257);
		SpectralCreatures.add(NpcID.ANKOU_7864);
		SpectralCreatures.add(NpcID.ASYN_SHADE);
		SpectralCreatures.add(NpcID.ASYN_SHADOW);
		SpectralCreatures.add(NpcID.ASYN_SHADOW_5632);
		SpectralCreatures.add(NpcID.BANSHEE);
		SpectralCreatures.add(NpcID.BERSERK_BARBARIAN_SPIRIT);
		SpectralCreatures.add(NpcID.DARK_ANKOU);
		SpectralCreatures.add(NpcID.DEATH_WING);
		SpectralCreatures.add(NpcID.DEVIANT_SPECTRE);
		SpectralCreatures.add(NpcID.DHAROK_THE_WRETCHED);
		SpectralCreatures.add(NpcID.DHAROK_THE_WRETCHED_12317);
		SpectralCreatures.add(NpcID.DHAROK_THE_WRETCHED_12323);
		SpectralCreatures.add(NpcID.DHAROK_THE_WRETCHED_12447);
		SpectralCreatures.add(NpcID.ENRAGED_BARBARIAN_SPIRIT);
		SpectralCreatures.add(NpcID.EVIL_SPIRIT);
		SpectralCreatures.add(NpcID.FEROCIOUS_BARBARIAN_SPIRIT);
		SpectralCreatures.add(NpcID.FIYR_SHADE);
		SpectralCreatures.add(NpcID.FIYR_SHADOW);
		SpectralCreatures.add(NpcID.FORGOTTEN_SOUL);
		SpectralCreatures.add(NpcID.FORGOTTEN_SOUL_10524);
		SpectralCreatures.add(NpcID.FORGOTTEN_SOUL_10525);
		SpectralCreatures.add(NpcID.FORGOTTEN_SOUL_10526);
		SpectralCreatures.add(NpcID.FORGOTTEN_SOUL_10534);
		SpectralCreatures.add(NpcID.FORGOTTEN_SOUL_10535);
		SpectralCreatures.add(NpcID.FORGOTTEN_SOUL_10536);
		SpectralCreatures.add(NpcID.FORGOTTEN_SOUL_10537);
		SpectralCreatures.add(NpcID.FORGOTTEN_SOUL_10544);
		SpectralCreatures.add(NpcID.FORGOTTEN_SOUL_10545);
		SpectralCreatures.add(NpcID.GHAST);
		SpectralCreatures.add(NpcID.GHAST_946);
		SpectralCreatures.add(NpcID.GHAST_5622);
		SpectralCreatures.add(NpcID.GHAST_5623);
		SpectralCreatures.add(NpcID.GHAST_5624);
		SpectralCreatures.add(NpcID.GHAST_5625);
		SpectralCreatures.add(NpcID.GHAST_5626);
		SpectralCreatures.add(NpcID.GHAST_5627);
		SpectralCreatures.add(NpcID.GHOST_5370);
		SpectralCreatures.add(NpcID.GHOST_3975);
		SpectralCreatures.add(NpcID.GHOST_3976);
		SpectralCreatures.add(NpcID.GHOST_3977);
		SpectralCreatures.add(NpcID.GHOST_3978);
		SpectralCreatures.add(NpcID.GHOST_3979);
		SpectralCreatures.add(NpcID.GHOST_86);
		SpectralCreatures.add(NpcID.GHOST_87);
		SpectralCreatures.add(NpcID.GHOST_88);
		SpectralCreatures.add(NpcID.GHOST_89);
		SpectralCreatures.add(NpcID.GHOST_90);
		SpectralCreatures.add(NpcID.GHOST_91);
		SpectralCreatures.add(NpcID.GHOST_92);
		SpectralCreatures.add(NpcID.GHOST_93);
		SpectralCreatures.add(NpcID.GHOST_94);
		SpectralCreatures.add(NpcID.GHOST_95);
		SpectralCreatures.add(NpcID.GHOST_96);
		SpectralCreatures.add(NpcID.GHOST_97);
		SpectralCreatures.add(NpcID.GHOST_98);
		SpectralCreatures.add(NpcID.GHOST_99);
		SpectralCreatures.add(NpcID.GHOST_472);
		SpectralCreatures.add(NpcID.GHOST_473);
		SpectralCreatures.add(NpcID.GHOST_474);
		SpectralCreatures.add(NpcID.GHOST_506);
		SpectralCreatures.add(NpcID.GHOST_507);
		SpectralCreatures.add(NpcID.GHOST_7263);
		SpectralCreatures.add(NpcID.GHOST_7264);
		SpectralCreatures.add(NpcID.GHOST_3625);
		SpectralCreatures.add(NpcID.GHOST_2531);
		SpectralCreatures.add(NpcID.GHOST_2532);
		SpectralCreatures.add(NpcID.GHOST_2533);
		SpectralCreatures.add(NpcID.GHOST_2534);
		SpectralCreatures.add(NpcID.GHOST_2527);
		SpectralCreatures.add(NpcID.GHOST_2528);
		SpectralCreatures.add(NpcID.GHOST_2529);
		SpectralCreatures.add(NpcID.GHOST_2530);
		SpectralCreatures.add(NpcID.GUTHAN_THE_INFESTED);
		SpectralCreatures.add(NpcID.GUTHAN_THE_INFESTED_12318);
		SpectralCreatures.add(NpcID.GUTHAN_THE_INFESTED_12324);
		SpectralCreatures.add(NpcID.IRVIG_SENAY);
		SpectralCreatures.add(NpcID.KARIL_THE_TAINTED);
		SpectralCreatures.add(NpcID.KARIL_THE_TAINTED_12319);
		SpectralCreatures.add(NpcID.KARIL_THE_TAINTED_12325);
		SpectralCreatures.add(NpcID.KASONDE_THE_CRAVEN_12332);
		SpectralCreatures.add(NpcID.KASONDE_THE_CRAVEN);
		SpectralCreatures.add(NpcID.KETLA_THE_UNWORTHY);
		SpectralCreatures.add(NpcID.KETLA_THE_UNWORTHY_12330);
		SpectralCreatures.add(NpcID.LOAR_SHADE);
		SpectralCreatures.add(NpcID.LOAR_SHADOW);
		SpectralCreatures.add(NpcID.NAZASTAROOL_5355);
		SpectralCreatures.add(NpcID.NAZASTAROOL_6400);
		SpectralCreatures.add(NpcID.OTHERWORLDLY_BEING);
		SpectralCreatures.add(NpcID.PERSTEN_THE_DECEITFUL);
		SpectralCreatures.add(NpcID.PHANTOM_MUSPAH);
		SpectralCreatures.add(NpcID.PHANTOM_MUSPAH_12078);
		SpectralCreatures.add(NpcID.PHANTOM_MUSPAH_12079);
		SpectralCreatures.add(NpcID.PHANTOM_MUSPAH_12080);
		SpectralCreatures.add(NpcID.PHANTOM_MUSPAH_12082);
		SpectralCreatures.add(NpcID.PHRIN_SHADE);
		SpectralCreatures.add(NpcID.PHRIN_SHADOW);
		SpectralCreatures.add(NpcID.RANALPH_DEVERE);
		SpectralCreatures.add(NpcID.REPUGNANT_SPECTRE);
		SpectralCreatures.add(NpcID.REVENANT_CYCLOPS);
		SpectralCreatures.add(NpcID.REVENANT_DARK_BEAST);
		SpectralCreatures.add(NpcID.REVENANT_DEMON);
		SpectralCreatures.add(NpcID.REVENANT_DRAGON);
		SpectralCreatures.add(NpcID.REVENANT_GOBLIN);
		SpectralCreatures.add(NpcID.REVENANT_HELLHOUND);
		SpectralCreatures.add(NpcID.REVENANT_HOBGOBLIN);
		SpectralCreatures.add(NpcID.REVENANT_IMP);
		SpectralCreatures.add(NpcID.REVENANT_KNIGHT);
		SpectralCreatures.add(NpcID.REVENANT_MALEDICTUS);
		SpectralCreatures.add(NpcID.REVENANT_ORK);
		SpectralCreatures.add(NpcID.REVENANT_PYREFIEND);
		SpectralCreatures.add(NpcID.RIYL_SHADE);
		SpectralCreatures.add(NpcID.RIYL_SHADOW);
		SpectralCreatures.add(NpcID.RIYL_SHADOW_5631);
		SpectralCreatures.add(NpcID.SAN_TOJALON);
		SpectralCreatures.add(NpcID.SCREAMING_BANSHEE);
		SpectralCreatures.add(NpcID.SCREAMING_TWISTED_BANSHEE);
		SpectralCreatures.add(NpcID.SHADE);
		SpectralCreatures.add(NpcID.SHADE_7258);
		SpectralCreatures.add(NpcID.SHADE_6740);
		SpectralCreatures.add(NpcID.SPIRITUAL_MAGE);
		SpectralCreatures.add(NpcID.SPIRITUAL_MAGE_2244);
		SpectralCreatures.add(NpcID.SPIRITUAL_MAGE_3161);
		SpectralCreatures.add(NpcID.SPIRITUAL_MAGE_3168);
		SpectralCreatures.add(NpcID.SPIRITUAL_MAGE_11292);
		SpectralCreatures.add(NpcID.SPIRITUAL_RANGER);
		SpectralCreatures.add(NpcID.SPIRITUAL_RANGER_2242);
		SpectralCreatures.add(NpcID.SPIRITUAL_RANGER_3160);
		SpectralCreatures.add(NpcID.SPIRITUAL_RANGER_3167);
		SpectralCreatures.add(NpcID.SPIRITUAL_RANGER_11291);
		SpectralCreatures.add(NpcID.SPIRITUAL_WARRIOR);
		SpectralCreatures.add(NpcID.SPIRITUAL_WARRIOR_2243);
		SpectralCreatures.add(NpcID.SPIRITUAL_WARRIOR_3159);
		SpectralCreatures.add(NpcID.SPIRITUAL_WARRIOR_3166);
		SpectralCreatures.add(NpcID.SPIRITUAL_WARRIOR_11290);
		SpectralCreatures.add(NpcID.SULPHUR_NAGUA);
		SpectralCreatures.add(NpcID.SULPHUR_NAGUA_13033);
		SpectralCreatures.add(NpcID.THE_FORSAKEN_ASSASSIN);
		SpectralCreatures.add(NpcID.TORAG_THE_CORRUPTED);
		SpectralCreatures.add(NpcID.TORAG_THE_CORRUPTED_12320);
		SpectralCreatures.add(NpcID.TORAG_THE_CORRUPTED_12326);
		SpectralCreatures.add(NpcID.TORTURED_SOUL);
		SpectralCreatures.add(NpcID.TREE_SPIRIT);
		SpectralCreatures.add(NpcID.TREE_SPIRIT_6380);
		SpectralCreatures.add(NpcID.TREE_SPIRIT_HARD);
		SpectralCreatures.add(NpcID.TREUS_DAYTH_6359);
		SpectralCreatures.add(NpcID.TREUS_DAYTH_HARD);
		SpectralCreatures.add(NpcID.TWISTED_BANSHEE);
		SpectralCreatures.add(NpcID.URIUM_SHADE);
		SpectralCreatures.add(NpcID.URIUM_SHADOW);
		SpectralCreatures.add(NpcID.VERAC_THE_DEFILED);
		SpectralCreatures.add(NpcID.VERAC_THE_DEFILED_12321);
		SpectralCreatures.add(NpcID.VERAC_THE_DEFILED_12327);
	}
}


